const ML_AUTH_API='https://rgdnhcmeuhkyltzpbola.supabase.co/functions/v1/marktluecken-auth';
const ML_AUTH_TOKEN_KEY='marktluecken_auth_token';
function mlToken(){return localStorage.getItem(ML_AUTH_TOKEN_KEY)||''}
function mlSession(){try{return JSON.parse(localStorage.getItem('marktluecken_session_data')||'null')}catch{return null}}
async function mlApi(action,body){const r=await fetch(`${ML_AUTH_API}?action=${encodeURIComponent(action)}`,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(mlToken()?{Authorization:`Bearer ${mlToken()}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function mlSetSession(data){localStorage.setItem(ML_AUTH_TOKEN_KEY,data.token);localStorage.setItem('marktluecken_session_data',JSON.stringify(data))}
async function mlLogout(){try{await mlApi('logout')}catch{}localStorage.removeItem(ML_AUTH_TOKEN_KEY);localStorage.removeItem('marktluecken_session_data');location.href='index.html'}
function mlIsAdmin(){const s=mlSession();return !!(s&&s.role==='admin'&&mlToken())}
function mlEscape(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function mlApplyEmergency(){try{const adminLogin=location.pathname.endsWith('/login.html')&&new URLSearchParams(location.search).get('admin')==='1';if(mlIsAdmin()||adminLogin)return;const state=await mlApi('public-state');if(!state.emergency_lock)return;document.documentElement.classList.add('emergency-active');const overlay=document.createElement('div');overlay.id='mlEmergencyOverlay';overlay.innerHTML=`<div class="emergency-modal" role="alertdialog" aria-modal="true"><div class="emergency-icon">!</div><p class="eyebrow">SYSTEMSTATUS</p><h2>Website gesperrt</h2><p>${mlEscape(state.emergency_message)}</p></div>`;document.body.appendChild(overlay);document.body.classList.add('emergency-locked');const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode()){if(!overlay.contains(walker.currentNode)&&walker.currentNode.nodeValue.trim())nodes.push(walker.currentNode)}const chars='█▓▒░?#@%';for(const n of nodes){const original=n.nodeValue;n.nodeValue=original.split('').map((c,i)=>c===' '||c==='\n'?' ':chars[(i*7+original.length)%chars.length]).join('')}document.querySelectorAll('a,button,input,textarea,select').forEach(el=>{if(!overlay.contains(el)){el.setAttribute('tabindex','-1');el.style.pointerEvents='none'}})}catch(e){console.warn('Emergency status:',e)}}
function mlAddEmergencyStyles(){if(document.getElementById('mlEmergencyStyles'))return;const s=document.createElement('style');s.id='mlEmergencyStyles';s.textContent=`body.emergency-locked{overflow:hidden;background:#080808!important}#mlEmergencyOverlay{position:fixed;inset:0;z-index:2147483647;background:rgba(0,0,0,.94);display:grid;place-items:center;padding:24px}#mlEmergencyOverlay .emergency-modal{width:min(620px,100%);box-sizing:border-box;text-align:center;padding:48px 28px;background:#111;color:#fff;border:1px solid #444;border-radius:28px;box-shadow:0 30px 100px rgba(0,0,0,.8)}#mlEmergencyOverlay .emergency-icon{width:58px;height:58px;border:2px solid #fff;border-radius:50%;display:grid;place-items:center;margin:0 auto 24px;font-size:30px;font-weight:900}#mlEmergencyOverlay h2{font-size:clamp(34px,8vw,64px);margin:8px 0 16px;letter-spacing:-.05em}#mlEmergencyOverlay p:not(.eyebrow){font-size:18px;line-height:1.6;color:#c9c9c9;margin:0}.emergency-active *{user-select:none}`;document.head.appendChild(s)}
mlAddEmergencyStyles();mlApplyEmergency();